version: '2'
services:
  nginx:
    image: chrisqueen/dockermagento-nginx
    #fip: 209.177.92.66
    fip: auto
    size: s4
    hostname: dockermagento-nginx
    ports:
      - "80:80"
      - "443:443"
    command: "nginx -g 'daemon off;'"