version: '2'
services:
  nginx:
    image: chrisqueen/dockermagento-nginx
    #fip: 209.177.92.66
    fip: auto
    size: s4
    hostname: dockermagento-nginx
    ports:
      - "80:80"
      - "443:443"
    noauto_volume: true
    volumes:
      - nginxcodessl:/etc/nginx/ssl
volumes:
  nginxcodessl:
    volumes:
      - https://raw.githubusercontent.com/gitchrisqueen/dockermagento/master/config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
      - https://raw.githubusercontent.com/gitchrisqueen/dockermagento/master/config/ssl/cert.key:/etc/nginx/ssl/cert.key


      - https://raw.githubusercontent.com/gitchrisqueen/dockermagento/master/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - https://raw.githubusercontent.com/gitchrisqueen/dockermagento/master/config/nginx/sites-enabled/default.conf:/etc/nginx/conf.d/default.conf

      - https://raw.githubusercontent.com/gitchrisqueen/dockermagento/master/config/nginx/includes:/etc/nginx/includes

      - https://raw.githubusercontent.com/gitchrisqueen/dockermagento/master/config/nginx/custom-locations:/etc/nginx/custom-locations

